name: test
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - python=3.11
  - scipy
  - matplotlib
  - nb_conda_kernels
  - bokeh
  - seaborn
  - jupyterlab
  - xlrd
  - jupyter
  - pypandoc
  - aiohttp
  - backoff
  - tqdm
  - statsmodels
  - plotly
  - dash
  - openpyxl
  - geopandas
